title: CoderDojo Konan
description: >- 
  CoderDojo は7〜17歳の子どもを対象にした無料で参加できるプログラミング道場(サークル)です。
  CoderDojoでは、Ninja同士（参加している子供をNinjaといいます。）で教えあったり、
  わからないことがあれば、現役プログラマーを中心としたメンターさんに質問したりできます。
baseurl: ""
url: "//coderdojo-konan.jp"

facebook_url: https://www.facebook.com/CoderDojo.Konan/
twitter_id: CoderDojoKonan_
instagram_id: coderdojo.konan
github_id: coderdojo-konan

collections:
  pages:
    output: true

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
